permalink: pretty
markdown: kramdown
twitter: 2faorg
social_image: https://repository-images.githubusercontent.com/17724730/63495880-b408-11e9-8cc4-03451aa4cc14
theme_color: "#39CCCC"
exclude:
  - EXCLUSION.md
  - Gemfile
  - "*.lock"
  - LICENSE
  - README.md
  - Rakefile
  - vendor/
  - scripts/
  - tests/
  - api/v2/README.md
  - ".*"
theme: null
